---
# tasks file for cisco_router
- name: DISPLAYING THE RUNNING-CONFIG
  ios_command:
    commands:
      - show running-config
  register: config
- name: SAVE OUTPUT TO ./backups/
  copy:
    content: "{{ config.stdout[0] }}"
    dest: "backups/show_running-config.txt"
- name: SET IPV6 ADDRESS
  ios_config:
    parents: "interface GigabitEthernet1"
    lines:
      - description IPv6 ADDRESS
      - ipv6 address 2001:db8:acad:1::1/64
      - ipv6 address fe80::1:1 link-local
- name: SHOW IPV6 INTERFACE BRIEF
  ios_command:
    commands:
      - show ipv6 interface brief
  register: output
- name: SAVE OUTPUT backups/IPv6_output_{{ inventory_hostname }}.txt
  copy:
    content: "{{ output.stdout[0] }}"
    dest: "backups/IPv6_output_{{ inventory_hostname }}.txt"
